name: Run Bash Command

on:
  workflow_dispatch:

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Run Bash Command
        run: |
          echo "Let's see if we can get some host info"
          free -h
          lscpu
