# This is a basic workflow to help you get started with Actions

name: Push content to Sharepoint

on:
  workflow_dispatch:



jobs:
  PushToSharepoint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
        pandoc --version

    # Convert md files to http 
    - name: Convert Markdown to HTML
      run: |
        mkdir output
        pandoc --version
        find mdfiles -name "*.md" -exec sh -c 'pandoc {} -o "output/$(basename {} .md)".html ' \;
        ls -R
      
